MODULE_TYPE := executable

DEPENDENCIES += drivers/mcu/rp2040
DEPENDENCIES += mal/interface
DEPENDENCIES += mal/rp2040

STATIC_LIBS += microjava_rp2040_driver microjava_mal_rp2040

OUTPUT 		  := microjava
LINKER_SCRIPT := default.ld